Checkpoint 1
artlvruran/freelance_platform pull request #1
Opened 2024-03-17 20:44 UTC by artlvruran

2024-04-02 08:04 UTC, NikitaPogadaev requested changes

2024-04-02 08:04 UTC, NikitaPogadaev commented on src/constants.h
> +#ifndef FREELANCEPLATFORM_SRC_CONSTANTS_H_
зачем используешь ifndef вместе с pragma once?

2024-04-15 20:03 UTC, artklyachin commented
Сделай описание классов

2024-04-15 20:08 UTC, artklyachin commented
README - как запускать проект, запуск должен быть простой. Необходимо указать версию языка, при помощи которого запускается проект

2024-05-04 20:23 UTC, artklyachin commented on diagrams/frealnceplatform Class diagram.png
Слишком много пересечений в диаграмме, её сложно понимать. Передвинь детали так, чтобы стало лучше

2024-05-04 20:23 UTC, artklyachin commented on main.cpp
> +  sql << "select * from users where username == :username", soci::into(john), soci::use(std::string("john"));
Сделай отдельный класс для работы с sql. Запросы к базе данных не должны идти на прямую

2024-05-04 20:23 UTC, artklyachin commented on diagrams/frealnceplatform Use Case diagram.png
Надо ли уведомить заказчика о подаче заявки?
Что происходит при смене фазы над проектом?
Нужно ли регистрироваться Заказчику и исполнителю? 
Сделай подробнее, распиши сценарии использования

2024-05-04 20:23 UTC, artklyachin commented on diagrams/frealnceplatform Class diagram.png
Где класс для обычных юзеров?

2024-05-04 20:23 UTC, artklyachin commented on diagrams/frealnceplatform Class diagram.png
Как проект связан с заказчиком?

2024-05-04 20:23 UTC, artklyachin commented on src/bid.h
> +  static void to_base(const Bid& p, values& v, indicator& ind) {
Однобуквенная переменная. Перемнные должны называться осмысленно

2024-05-04 20:23 UTC, artklyachin commented on src/bid_state.cpp
> +  return "approved";
Можешь оформить статусы в виде enum class

2024-05-05 21:25 UTC, artlvruran commented on src/bid_state.cpp
> +  return "approved";
Точно ли стоит это делать? Я сделал эти функции для конвертации класса состояния в строку, то есть в удобочитаемый для бд формат. Если строки заменить на enum-ы,то при обращении к бд придётся добавить ещё условных ветвлений.

2024-05-05 21:29 UTC, artlvruran commented on diagrams/frealnceplatform Class diagram.png
Заказчик публикует проект, меняет состояния работы над ним, и принимает или отклоняет заявки фрилансеров на участие в проекте.

2024-05-05 21:31 UTC, artlvruran commented on diagrams/frealnceplatform Class diagram.png
Всего есть только два вида юзеров: Заказчик(Contractor) и Работник(Employee). Взаимодействовать с платформой можно только через них.

2024-05-06 08:32 UTC, artlvruran commented on diagrams/frealnceplatform Use Case diagram.png
Добавил в README.

2024-05-07 13:28 UTC, artklyachin commented
Пренеси код с первой итерации на вторую итерацию, чтобы мы могли к ней перейти

2024-05-07 13:36 UTC, artklyachin commented
Напиши, какие паттерны программирования ты используешь в readme (это условие 1ой итерации)

2024-05-13 08:18 UTC, artklyachin commented on main.cpp
> +  sql << "select * from users where username == :username", soci::into(john), soci::use(std::string("john"));
для работы с sql лучше завести отдельный класс

2024-05-13 08:18 UTC, artklyachin commented on diagrams/frealnceplatform Class diagram.png
Спасибо, стало лучше

2024-05-13 08:18 UTC, artklyachin commented on main.cpp
> +  sql << "select * from users where username == :username", soci::into(john), soci::use(std::string("john"));
Это конечно не обязательно, но это является хорошей практикой по нескольким причинам: Инкапсуляция, Отсутствие повторяющегося кода, Удобная Тестируемость, Простота внесения изменений в структуру базы данных. Но я не заставляю тебя это исправлять

2024-05-14 17:56 UTC, merged